### ISSUE TITLE
Remove your token.

### ISSUE THREAD

**Issue by Tylertron1998** [UphillLobster/Benzi-the-Discord-Bot#1]
I can see your token on this PUBLIC repo. Remove it and go to discordapp.com/developers/applications/me and reset your bots token. Anyone can log in and control your bot.

Do NOT leave tokens on public repos.

**Comment by armedturret** [comment]
This has been fixed. (We learned the hard way after our bot got hacked.) We now require a separate token.json file.

**Comment by armedturret** [comment]
It was also a test bot's token so not much damage was done.
